version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify labels for pull requests for version updates
    labels:
      - "dependencies"
      - "npm"
    # Limit the number of open pull requests for version updates
    open-pull-requests-limit: 10
    # Allow up-to-date branches to be rebased
    rebase-strategy: "auto"
    # Specify the version update strategy
    versioning-strategy: "auto"
    # Group all minor and patch updates together
    groups:
      dependencies:
        patterns:
          - "*"
    # Set reviewers for the pull requests
    reviewers:
      - "yourusername"
    # Set assignees for the pull requests
    assignees:
      - "yourusername"
    # Set commit message prefix
    commit-message:
      prefix: "npm"
      include: "scope"
    # Set labels for the pull requests
    labels:
      - "dependencies"
      - "npm"
    # Set milestone for the pull requests
    milestone: 1
    # Set target branch for the pull requests
    target-branch: "main"
    # Set allowed updates
    allowed-updates:
      # Allow all updates
      - match:
          update-type: "all"
    # Set ignored updates
    ignore:
      # Ignore updates to packages that are not in the allowed list
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Set security updates
    security-updates-only: false
    # Set security advisories
    security-advisories:
      # Enable security advisories
      enabled: true
    # Set security updates
    security-updates:
      # Enable security updates
      enabled: true
    # Set security update strategy
    security-update-strategy: "auto"
    # Set security update labels
    security-update-labels:
      - "security"
    # Set security update reviewers
    security-update-reviewers:
      - "yourusername"
    # Set security update assignees
    security-update-assignees:
      - "yourusername"
    # Set security update commit message prefix
    security-update-commit-message:
      prefix: "security"
      include: "scope"
    # Set security update milestone
    security-update-milestone: 1
    # Set security update target branch
    security-update-target-branch: "main"
    # Set security update allowed updates
    security-update-allowed-updates:
      # Allow all updates
      - match:
          update-type: "all"
    # Set security update ignored updates
    security-update-ignore:
      # Ignore updates to packages that are not in the allowed list
      - dependency-name: "*"
        update-types: ["version-update:semver-major"] 